### ISSUE TITLE
Plugin does not seem to support private GKE clusters

### ISSUE THREAD

**Issue by mzwennes** [replicatedhq/outdated#88]
We have a setup with a private GKE cluster and a bastion through which we connect to the GKE cluster. In order to make this work we set the `proxy-url` value in the Kubeconfig. 

The Kubeconfig looks something like this:
```
- cluster:
    certificate-authority-data: XXX
    proxy-url: http://localhost:8884
    server: https://172.11.0.6
  name: cluster
```

This works fine for default `kubectl` commands: 

```
➜ k get ns
NAME               STATUS   AGE
bsr                Active   301d
cert-manager       Active   342d
cluster-health     Active   342d
default            Active   343d
```

However the `kubectl outdated` command seems to throw a timeout error:

```
➜ k outdated
  Searching for images ⠴failed to list namespaces: Get "https://172.11.0.6/api/v1/namespaces": dial tcp 172.11.0.6:443: i/o timeout
```

What I have tried so far:
- Test on a cluster with public access (works)
- Manually passing the `--kubeconfig` param (does not work)

Any ideas if this is related to the `oudated` plugin not properly handling proxies?
